micronaut:
  application:
    name: nossaCasaDoCodigo

datasources:
  default:
    url: ${DB_URL:`jdbc:mysql://localhost:3306/nossa-casa-do-codigo`}
    driverClassName: com.mysql.jdbc.Driver
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:zupper}

jpa:
  hibernate.ddl-auto: update
  generate-ddl: true
  show-sql: true

jpa.default.properties.hibernate.hbm2ddl.auto: update
